modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="GNU LESSER GENERAL PUBLIC LICENSE"
issueTrackerURL="https://github.com/suchipi/AlexsShoebill/issues" #optional
[[mods]] #mandatory
modId="alexsshoebill" #mandatory
version="1.18.6" #mandatory
displayName="Alex's Shoebill" #mandatory
displayURL="https://github.com/suchipi/AlexsShoebill" #optional
authors="Alexthe668, Carro1001" #optional
description='''The shoebills from Alex's Mobs.'''
[[dependencies.alexsshoebill]] #optional
    # the modid of the dependency
    modId="citadel" #mandatory
    # Does this dependency have to exist - if not, ordering below must be specified
    mandatory=true #mandatory
    # The version range of the dependency
    versionRange="[1.11.1,)" #mandatory
    # An ordering relationship for the dependency - BEFORE or AFTER required if the relationship is not mandatory
    ordering="AFTER"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
[[dependencies.alexsshoebill]]
    modId="forge"
    mandatory=true
    versionRange="[36.0.42,)"
    ordering="NONE"
    side="BOTH"
[modproperties.alexsshoebill]
    catalogueItemIcon="alexsshoebill:cosmic_cod"
